name: Preview Build and Deploy

on:
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Install Node.Js
    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 22
    
    # Step 3: Install dependencies
    - name: Install Dependencies and build
      working-directory: ./
      env:
        CI: false
      run: |
        npm install
        npm run build

    # Step 4: Copy server files and build folder to dev-preview 
    - name: Deploy to Dev Preview branch
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        mkdir deploy
        cp -R server deploy/
        cp -R build/* deploy/
        
        cd deploy
        git init
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"

        git add .
        git commit -m "Deploy dev-preview build from dev"
        git branch -M dev-preview
        git push -f https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/ZNGR-DYNAMICS/BanhMiBros.git dev-preview
