name: Preview Test Build Deploy

on:
  workflow_dispatch:

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
    # 1 Checkout repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # 2 Install node.js
    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 22
    
    # 3 Install dependencies
    - name: Install dependencies
      run: npm install

    # 4 Run tests
    - name: Run tests
      run: npm test

    # 5 Build app
    - name: Build app
      env:
        CI: false
      run: npm run build
    
    # 6 Create .htaccess for SPA routing
    - name: Create .htaccess
      run: |
        echo '<IfModule mod_rewrite.c>' > dist/.htaccess
        echo '  RewriteEngine On' >> dist/.htaccess
        echo '  RewriteBase /' >> dist/.htaccess
        echo '  RewriteCond %{REQUEST_FILENAME} -f [OR]' >> dist/.htaccess
        echo '  RewriteCond %{REQUEST_FILENAME} -d' >> dist/.htaccess
        echo '  RewriteRule ^ - [L]' >> dist/.htaccess
        echo '  RewriteRule ^ index.html [L]' >> dist/.htaccess
        echo '</IfModule>' >> dist/.htaccess
        echo 'Created dist/.htaccess'
        cat dist/.htaccess # Temporary Logging
    
    # 7 Copy api files and dist folder to preview
    - name: Deploy to preview branch
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        mkdir dist
        cp -R api dist/
        cp -R _dist/* dist/
        
        cd dist
        git init
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"

        git add .
        git commit -m "Deploy preview build from dev"
        git branch -M preview
        git push -f https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/ZNGR-DYNAMICS/banhmibros-vite.git preview